name: Grid Site
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.5
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eaeaea'
    - '#a19fa2'
    - '#e26630'
    - '#000000'
    - '#237ead'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
